### ISSUE TITLE
In SentimentLDA.py file dill.dump Error Line 136

### ISSUE THREAD

**Issue by abdullasirajudeen** [ayushjain91/Sentiment-LDA#2]
wordOccurenceMatrix = train_data_features.toarray()
        if saveAs:
            dill.dump([wordOccurenceMatrix, self.vectorizer], open(saveAs, 'w'))
        return wordOccurenceMatrix

will give error 

Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 119, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\debugger.py", line 39, in debug
    run()
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "H:\Main Project\ProductAnalysisApp\amazon_demo.py", line 34, in <module>
    sampler.run(reviews, 200, "./../data/sorted_data_acl/dvd_reviews.dll", True)
  File "H:\Main Project\ProductAnalysisApp\sentimentLDA.py", line 240, in run
    self._initialize_(reviews, saveAs, saveOverride)
  File "H:\Main Project\ProductAnalysisApp\sentimentLDA.py", line 144, in _initialize_
    self.wordOccuranceMatrix = self.processReviews(reviews, saveAs, saveOverride)
  File "H:\Main Project\ProductAnalysisApp\sentimentLDA.py", line 136, in processReviews
    dill.dump([wordOccurenceMatrix, self.vectorizer], open(saveAs, 'w'))
  File "H:\Main Project\ProductAnalysisApp\env_product\lib\site-packages\dill\_dill.py", line 259, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "H:\Main Project\ProductAnalysisApp\env_product\lib\site-packages\dill\_dill.py", line 445, in dump
    StockPickler.dump(self, obj)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\pickle.py", line 434, in dump
    self.write(PROTO + pack("<B", self.proto))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\pickle.py", line 229, in write
    return self.file_write(data)
TypeError: write() argument must be str, not bytes

**Comment by SuicV** [comment]
I'm using python 3.8. I faced the same bug. The issue was in `open` function, instead of calling `open` function with `w` mode, you have to call it with write binary mode `wb`.

code :
```
wordOccurenceMatrix = train_data_features.toarray()
if saveAs:
       dill.dump([wordOccurenceMatrix, self.vectorizer], open(saveAs, 'wb'))
return wordOccurenceMatrix
```
